name: Run Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: copy to doc
      run: |
       cp -pr build/distributions doc/
       git config user.name "Soeking"
       git config user.email "great.from.g@gmail.com"
       git remote set-url origin https://github.com/Soeking/riversi.git
       git add .
       git commit -m "build"
       git push origin master
